#! /bin/sh

set -x
aclocal -I config
case `uname` in
 Darwin) glibtoolize --force --copy --ltdl ;;
     *)  libtoolize --force --copy --ltdl ;;
esac
#libtoolize --force --copy --ltdl
autoheader
automake --add-missing --copy
autoconf
