S = 14
all:
	font2vfm STIXGeneral.otf $(S)
	mv STIXGeneral.otf.vfm STIX.vfm
	font2vfm STIXGeneralBol.otf $(S)
	mv STIXGeneralBol.otf.vfm STIX_b.vfm
	font2vfm STIXGeneralItalic.otf $(S)
	mv STIXGeneralItalic.otf.vfm STIX_i.vfm
	font2vfm STIXGeneralBolIta.otf $(S)
	mv STIXGeneralBolIta.otf.vfm STIX_bi.vfm
